unique_ids:
  assets:
    standard-page.html: 4WPXOJDQAJIMXWQHRCCBL5SCVCKZ7HNY
    theme.css: TWHKL7YNID6SS6TGNWHF3DXBMLLROGKK
  forms:
    Client_list: '1761392065421341846000441.42474'
    Costing_sheet_base: VK6V62JSTW6OZFR4LQAZDW3ZAVGXUSGW
    Costing_sheet_home: 7F5YG2MPTKVC3J3ICWJW4VBOOBSWUCUO
    Costing_sheet_home.Creating_cost_sheet_page: RN2LRRZNMWQ3LA3IRB4W2HMF5ZSJ7SCE
    Costing_sheet_home.Creating_cost_sheet_page.a_Basic_information_page: YQD2IE2TD7E7SYSK5H7ILC36DNVZNK2X
    Costing_sheet_home.Creating_cost_sheet_page.b_Bom_page: VBMELJI2DYD5OWORPKIV3RTLQF6C5MWR
    Costing_sheet_home.Creating_cost_sheet_page.c_Processing_cost: IJTUAU2EMMQENIQBGPHZIXLTDR7NYQ6J
    Costing_sheet_home.Creating_cost_sheet_page.d_Overhead_cost: UYT4SCH7OQLWRQFIVPYTFZ55UNB3YN2J
    Costing_sheet_home.Creating_cost_sheet_page.e_Profit_scenarios: EDBJGV2WBB33ULAWADZMOQ6YOVUZRTBE
    Costing_sheet_home.RowTemplate1: ZWZE66IVW44DIRQA7MYAYLLWXY2MIWWN
    Deal: '1761391960671703756629457.2389'
    Home: DNP22X3TNU36IXO4FW2GWYDLINVJ3BQN
    Master_Mat: KIMSFIMDBFNFO6GGK3Q3R4BYI5ZAKE5L
    Master_Mat.RowTemplate1: TGX3ARPJZWLXMU2GRZ6Z7NWQGUWHT7P3
    Master_Mat.RowTemplate2: GD2WE2IU2GOFBLQQRLIJ3KKI3XX4XLMG
    Material_detail: '1762232363749242069688936.04575'
    Material_detail.material_sku_rowtemplate: XQPRO2LKNQ2NX6ZM2QATA7LPORVUTDMB
    Material_detail.version_history_itemtemplate: 32KWER7EHLPCCKMWGMCPZFB2R452AKBK
    Material_input_form: '1762246514081760660811976.6614'
    Material_input_form.Input_forms: CABDMQSLAU5FJZ4W52SWTFVIEWGI7Z7V
    Material_list: '176223201599762412789806.216'
    Material_list.MaterialCard: '1762400047405995510792459.7573'
    Material_sku_input_form: '1763095383048651596420106.4791'
    Opportunity: '1761391942918616178806726.4047'
    QMO: '17613920531692144854397.7878876'
  modules: {}
  scripts: {}
  server_modules:
    mat_detail: '1762507012634289144327609.31573'
    mat_input: DEORGFCBEOX6PXFPU2RSBH25IEZGRN2A
    mat_list: '1762415028890455059908817.8722'
    mock: '1762959754073343441814302.16034'
