unique_ids:
  assets:
    standard-page.html: 4WPXOJDQAJIMXWQHRCCBL5SCVCKZ7HNY
    theme.css: TWHKL7YNID6SS6TGNWHF3DXBMLLROGKK
  forms:
    Home: DNP22X3TNU36IXO4FW2GWYDLINVJ3BQN
    Material_detail: '1762232363749242069688936.04575'
    Material_detail.material_sku_rowtemplate: XQPRO2LKNQ2NX6ZM2QATA7LPORVUTDMB
    Material_detail.version_history_itemtemplate: '1764148267325154172073797.02036'
    Material_input_form: '1762246514081760660811976.6614'
    Material_input_form.Input_forms: '1764149286506192788483579.79382'
    Material_list: '176223201599762412789806.216'
    Material_list.MaterialCard: '1762336056821483042217454.3132'
    Material_sku_input_form: '1764149541024548151116321.81134'
    bingheng_Control_Panel: 35FZTUOY5IKXQL4QW3WHRUQ2KN6SG4I7
    bingheng_CreateProfile: TSUWXMPTI7FTEDLZGUYFAJCHYGOET2XP
    bingheng_Details_Page: Z4SKUI5VZYJEAY2JGLK7NBPZ6736KDFM
    bingheng_Style_SKU: GA6PJY5JYLW6L3GVRGBXYIZNHWLGIGOL
    bingheng_Style_SKU.Style_SKU_Sheet: KUXB4H6HM27DUR4P3OYEXKSYQK3RHP3H
    bingheng_logged_in: C34H4UQKCYLMQG7AZPZWSDM32QQR4QYK
    bingheng_logged_in.bingheng_logged_in_sheet: Z7V3HYZXGBTP34WDWU2A2W6WITQSFMN2
    costing_sheet_base: 2R5QB7EGESVWZZU5BSH5WRMZ7BWJAC3K
    costing_sheet_home: FEL5HFTV5KUK4G5WDMUL2ID4GRRWM5LU
    costing_sheet_home.ItemTemplate1: GKN55TQCIXSET2264AFQXZYAGUD7HAP5
    costing_sheet_home.RowTemplate3: CE7VAANNU24JBJJIO55FOAKKTJCVLMIV
    costing_sheet_home_line: 2DVHQZJXC3SQTAWXIDHQGBPM4QO3Q725
    creating_cost_sheet_page: 5LJ23GIHBF5UT5J3PB6OKO4N7F32JKKO
    creating_cost_sheet_page.a_Basic_information_page: M5EMXBFOVYEU5KDI3ZJ3KQNJ6FNB46XX
    creating_cost_sheet_page.a_Basic_information_page.ItemTemplate3: KUHOEFGLIY3B3MBTGIY3V7LGMMBSTZ5E
    creating_cost_sheet_page.a_Basic_information_page.add_currency_rates_item: KQAU3TS7RY7T4UMCAHBFRURUZ774WXGZ
    creating_cost_sheet_page.b_Bom_page: 6ATNZAW6CT6BFRKCHQERRVVIOEYKODLR
    creating_cost_sheet_page.b_Bom_page.bom_info_line: QZS2XWYBDOVFAKH5RZPFTID34FN4DF6X
    creating_cost_sheet_page.c_Processing_cost: JIZZDP6EULSWUJCTMFD2GQNXC7G7I6C5
    creating_cost_sheet_page.c_Processing_cost.processing_cost_line: V6XWA7ERYWWYXZLUBOKUPD3HG2635CVK
    creating_cost_sheet_page.d_Overhead_cost: SSNQIZBVN4M62BZFRAAZBRNGFSCYEAEB
    creating_cost_sheet_page.e_Profit_scenarios: 66JS3YBW3AZPXAANDD5BMB3XPT5PZPEA
    draft_to_be_deleted: 3FHY2IDBFPSYSSRVF2R75HFGQESMR4XS
    wanyan_ver_cost_sheet_details: '1762484347324621512864462.969'
    wanyan_ver_cost_sheet_details.BOM_rowtemplate: '1762484749460606510214332.3304'
    wanyan_ver_cost_sheet_details.Exchange_rates_rowtemplate: '1762486495973319579842865.9415'
    wanyan_ver_cost_sheet_details.Overhead_cost_rowtemplate: '1762493304190627878495335.4957'
    wanyan_ver_cost_sheet_details.Processing_costs_rowtemplate: '1762484933355357520417609.6758'
    wanyan_ver_cost_sheet_details.Version_history_itemtemplate: '1762499656214554359591675.5739'
    wanyan_ver_cost_sheet_edit_form: '1762502689469214175279107.09976'
    wanyan_ver_cost_sheet_edit_form.BOM_itemtemplate: '1762502708478932300578715.8165'
    wanyan_ver_cost_sheet_edit_form.Overhead_costs_itemtemplate: '1762506428329211070643998.17722'
    wanyan_ver_cost_sheet_edit_form.Processing_costs_itemtemplate: '1762502727579142109271783.0531'
    wanyan_ver_cost_sheet_input_form: '1762486658916842948285377.4646'
    wanyan_ver_cost_sheet_input_form.BOM_itemtemplate: '176248703171797396735154.61855'
    wanyan_ver_cost_sheet_input_form.Processing_costs_itemtemplate: '1762489655750671338078659.128'
    wanyan_ver_costing_sheet_overview: '1762482517025299779331947.2777'
    wanyan_ver_costing_sheet_overview.CostSheetCard: '1762483692036380843932060.1235'
  modules: {}
  scripts: {}
  server_modules:
    GlenCode: '1764148030760886408646489.1259'
    GlenCode.mat_detail: '1764148043355777166247424.2715'
    GlenCode.mat_input: '1764148726109865324868528.2965'
    GlenCode.mat_list: '1764148738595932919642339.361'
    GlenCode.mat_sku_input: '1764148745527994336415438.8383'
    JonsCode: '1763024011118754421530119.2096'
    JonsCode.ServerModule1: '1763543071115765173752219.1399'
    JonsCode.Testing: '1763087930240712947726824.1401'
    JonsCode.Testing_overhead_cost: 5DOEFEPSSXS46AQOQFXISDCP5VDC4A3X
    JonsCode.Testing_pricing_scenarios: BMPL3BJWVMLM6EFT42JCSAOXW7PYCZCG
    JonsCode.Testing_processing_cost: X5HJ6RT5N3JMPY4BYI44KGHKY2H22MEV
    JonsCode.bill_of_material: PUG4GLFI5MWHCEJNMZMFL3O3XTKWWXZK
    JonsCode.cost_sheet_helpers: KYH225GRJU7K3A2MZPZDKQ2HCI7VXVEO
    JonsCode.cost_sheets_main: GAO5CYGFKR6QQ6YZ5WVUUMCJX5CM6ZNX
    JonsCode.exchange_rate: ANSR534E2R2IDRWOJXK6S4NWAOK7XEYA
    JonsCode.overhead_cost: 5EMBKTEO573G3U7TF6V36L7JEW4PXAJD
    JonsCode.pricing_scenarios: MYJJ447SZQK6YSMAL5UVHOO5BK6TX2QJ
    JonsCode.processing_cost: OW2L4FSMHKELAEKXGACOX2XASL6RBUWO
    JonsCode.workflow: GBVHRHRICVMSPETSGIPWXFGTLJZECU2T
    bingheng_Servercode: W7A3DWCA72EZUFHH6SRTMI5KEQ53HVVA
