unique_ids:
  assets:
    standard-page.html: 4WPXOJDQAJIMXWQHRCCBL5SCVCKZ7HNY
    theme.css: TWHKL7YNID6SS6TGNWHF3DXBMLLROGKK
  forms:
    Home: DNP22X3TNU36IXO4FW2GWYDLINVJ3BQN
    costing_sheet_base: VK6V62JSTW6OZFR4LQAZDW3ZAVGXUSGW
    costing_sheet_home: 7F5YG2MPTKVC3J3ICWJW4VBOOBSWUCUO
    costing_sheet_home.ItemTemplate1: '1762335542986415042691387.59906'
    costing_sheet_home.RowTemplate3: '1762335428195137392558435.52145'
    costing_sheet_home_line: '1762378373524846483272617.8846'
    creating_cost_sheet_page: RN2LRRZNMWQ3LA3IRB4W2HMF5ZSJ7SCE
    creating_cost_sheet_page.a_Basic_information_page: YQD2IE2TD7E7SYSK5H7ILC36DNVZNK2X
    creating_cost_sheet_page.a_Basic_information_page.ItemTemplate3: '1762368477135312393120372.0403'
    creating_cost_sheet_page.a_Basic_information_page.add_currency_rates_item: '1762367658796536099380741.3491'
    creating_cost_sheet_page.b_Bom_page: VBMELJI2DYD5OWORPKIV3RTLQF6C5MWR
    creating_cost_sheet_page.b_Bom_page.bom_info_line: '1762481598238428437727529.374'
    creating_cost_sheet_page.c_Processing_cost: IJTUAU2EMMQENIQBGPHZIXLTDR7NYQ6J
    creating_cost_sheet_page.c_Processing_cost.processing_cost_line: '1762379226184639239648149.0819'
    creating_cost_sheet_page.d_Overhead_cost: UYT4SCH7OQLWRQFIVPYTFZ55UNB3YN2J
    creating_cost_sheet_page.e_Profit_scenarios: EDBJGV2WBB33ULAWADZMOQ6YOVUZRTBE
    draft_to_be_deleted: '17624245664278951908858.201406'
  modules: {}
  scripts: {}
  server_modules:
    add_exchange_rate: '1762368989852247631180293.74374'
    cost_sheet: '1762424426210122950563465.48772'
    view_exchange_rate_line: '176237319102784615321188.69252'
    view_processing_cost_line: '1762379618644661227702543.9282'
